server:
  port: ${PORT:0}
spring:
  application:
    name: stock-exchange
  datasource:
    password: sa
    url: jdbc:h2:mem:testdb
    username: sa
  boot:
      admin:
         client:
            url : http://localhost:7777/
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
eureka:
   client:
      register-with-eureka: true
      serviceUrl:
         defaultZone: http://localhost:8761/eureka
     
